import React from "react";
import { Quote, Sparkles, Star, User } from "lucide-react";
import { DepoimentoPremium } from "../types";

export default function SocialProof() {
  // Centerpiece smile asset generated by the AI
  const smileImage = "/src/assets/images/aesthetic_smile_1781525534740.jpg";

  const testimonials: DepoimentoPremium[] = [
    {
      id: "dep-1",
      nome: "Dr. Roberto Albuquerque",
      ocupacao: "Investidor de Mercado & Colecionador de Arte",
      texto: "Eu sempre temi o ambiente frio e barulhento das clínicas convencionais. No Itaguaí, a sedação consciente e a sutileza com que reconstruíram minhas pontas incisais me pareceram mais um retiro de repouso do que um consultório. Meu sorriso recuperou a vitalidade natural sem parecer falso.",
      tratamentoRealizado: "Reabilitação Estética Biomimética em Cerâmica",
      vibe: "Equilíbrio Sutil"
    },
    {
      id: "dep-2",
      nome: "Constança Valente",
      ocupacao: "Diretora Criativa & Curadora de Moda",
      texto: "Havia perdido minha autoestima devido ao desgaste e manchas. O parecer estético da IA compreendeu minhas proporções labiais perfeitamente, e a equipe esculpiu facetas feldspáticas com a refração de luz exata das pérolas. Um trabalho de mestre, executado sem dor alguma.",
      tratamentoRealizado: "Lentes de Contato Feldspáticas 0.2mm",
      vibe: "Brilho Intelectual"
    },
    {
      id: "dep-3",
      nome: "Mateus Schwyz",
      ocupacao: "Diplomata & Escritor",
      texto: "O verdadeiro luxo reside na invisibilidade da intervenção. Ninguém nota que fiz procedimentos, apenas comentam como minha fisionomia irradia saúde e serenidade. Isso é o que chamo de Engenharia do Sorriso.",
      tratamentoRealizado: "Alinhamento Invisível 3D Ativo & Laser de Gengiva",
      vibe: "Naturalidade Absoluta"
    }
  ];

  return (
    <section id="testimonials" className="py-24 bg-sage-150/50 border-t border-sage-200 relative overflow-hidden">
      {/* Decorative Blur Backgrounds */}
      <div className="absolute top-10 left-10 w-[300px] h-[300px] bg-gold-100/30 rounded-full blur-[100px] pointer-events-none" />
      <div className="absolute bottom-10 right-10 w-[300px] h-[300px] bg-sage-200/20 rounded-full blur-[100px] pointer-events-none" />

      <div className="max-w-7xl mx-auto px-6">
        
        {/* Core Layout Grid: Centerpiece Image on the left, Testimonials list on the right */}
        <div className="grid lg:grid-cols-12 gap-12 items-center">
          
          {/* Aesthetic center focus image frame */}
          <div className="lg:col-span-5 relative space-y-4">
            <div className="absolute -top-4 -left-4 w-16 h-16 border-t border-l border-gold-500/40" />
            <div className="absolute -bottom-4 -right-4 w-16 h-16 border-b border-r border-gold-500/40" />
            
            {/* The beautiful generated smile */}
            <div className="overflow-hidden rounded shadow-2xl relative aspect-[3/4] bg-sage-100">
              <img
                src={smileImage}
                alt="Sorriso Natural & Luminoso - Reabilitação de Luxo Itaguaí"
                className="w-full h-full object-cover grayscale opacity-90 hover:grayscale-0 transition-all duration-1000"
                referrerPolicy="no-referrer"
              />
              <div className="absolute inset-0 bg-gradient-to-t from-sage-950/40 via-transparent to-transparent pointer-events-none" />
            </div>

            <div className="text-left font-mono text-[9px] uppercase tracking-[0.25em] text-sage-600/60 p-1 flex justify-between">
              <span>[ FOTOGRAFIA RETRATO MACRO ]</span>
              <span>Matiz Translúcido Premium</span>
            </div>
          </div>

          {/* Testimonial Flow */}
          <div className="lg:col-span-7 space-y-12 text-left md:pl-6">
            
            <div className="space-y-3 pb-4 border-b border-sage-200">
              <span className="text-[10px] uppercase font-mono tracking-[0.35em] text-gold-600 font-semibold">Os Relatos de Cura</span>
              <h3 className="font-serif text-3xl sm:text-4xl text-sage-800 font-light tracking-tight leading-tight">
                A Sobriedade da <span className="italic font-normal">Autoestima Recuperada</span>
              </h3>
              <p className="text-xs sm:text-sm text-sage-800/60 font-light leading-relaxed">
                Nossos pacientes não relatam apenas intervenções cosméticas, mas sim o alívio profundo de fobias antigas, o conforto térmico de nossas cabines e a redescoberta da própria essência através da harmonia facial.
              </p>
            </div>

            <div className="space-y-8">
              {testimonials.map((test) => (
                <div 
                  key={test.id} 
                  className="p-6 bg-white border border-gold-100/45 shadow-lg rounded-sm relative space-y-4 hover:border-gold-500/20 transition-all duration-500"
                >
                  <Quote className="w-5 h-5 text-gold-500/30 absolute top-4 right-4" />
                  
                  {/* Testimonial Quote Statement */}
                  <p className="font-serif italic text-[14px] sm:text-[15px] text-sage-800/90 leading-relaxed font-light">
                    &ldquo;{test.texto}&rdquo;
                  </p>

                  {/* Testimonial Patient details */}
                  <div className="flex items-center justify-between border-t border-sage-100 pt-4 flex-wrap gap-2">
                    <div className="flex items-center gap-3">
                      <div className="w-8 h-8 rounded-full bg-sage-50 border border-gold-250 flex items-center justify-center">
                        <User className="w-4 h-4 text-gold-600" />
                      </div>
                      <div className="text-left">
                        <h5 className="text-[12px] text-sage-800 font-semibold">{test.nome}</h5>
                        <p className="text-[10px] text-sage-600/70 font-light">{test.ocupacao}</p>
                      </div>
                    </div>

                    <div className="bg-gold-50/50 border border-gold-500/10 rounded px-2.5 py-1 text-left">
                      <span className="text-[8px] uppercase tracking-widest font-mono text-gold-700 block">Tratamento</span>
                      <span className="text-[9px] text-sage-800 font-medium">{test.tratamentoRealizado}</span>
                    </div>
                  </div>
                </div>
              ))}
            </div>

          </div>

        </div>

      </div>
    </section>
  );
}
